### ISSUE TITLE
 Add all projects i maintain on Alpine Linux to newsboat for version tracking

### ISSUE THREAD

**Issue by maxice8** [maxice8/meltryllis#7]
- [x] appstream
- [x] gyp
- [x] exa
- [x] cbindgen
- [x] dxvk
- [x] cmark
- [x] buku
- [x] fd
- [x] elogind
- [x] lab
- [x] fish
- [x] falkon
- [x] dav1d
- [x] adapta-kde
- [x] glslang
- [x] gopass
- [x] gotop
- [x] grilo
- [ ] font-comfortaa
- [x] font-hermit-nerd
- [x] imgbrd-grabber
- [x] maim
- [ ] font-iosevka-nerd
- [x] editline
- [x] font-material-design-icons
- [ ] libpipeline
- [x] i3lock-color
- [x] hyperfine
- [x] libcotp
- [ ] man-db
- [ ] libdwarf
- [x] libb2
- [x] libbaseencode
- [x] libbloom
- [x] libcork
- [x] light-locker
- [x] libxkbcommon
- [x] lxqt-build-tools
- [x] libquotient
- [x] libsigc++3
- [x] libplacebo
- [x] slop
- [x] kvantum
- [x] otpclient
- [ ] perl-net-mpd
- [x] libxmlb
- [ ] mingw-w64-gcc-base
- [ ] mingw-w64-gcc
- [ ] mingw-w64-headers
- [ ] mingw-w64-crt
- [ ] mingw-w64-headers-bootstrap
- [ ] mingw-w64-winpthreads
- [x] py3-boltons
- [x] pulseaudio
- [x] libluv
- [x] py3-cleo
- [x] xdo
- [x] py3-coreapi
- [x] py3-clikit
- [x] py3-django-rest-swagger
- [x] py3-hypothesis
- [x] py3-dominate
- [x] py3-bleach
- [x] py3-cachy
- [x] paprefs
- [x] py3-invoke
- [x] powertop
- [ ] py3-iso8601
- [x] py3-pbkdf2
- [x] py3-gitdb2
- [x] py3-gitpython
- [x] py3-eliot
- [x] py3-gitlab
- [x] py3-pytest-runner
- [x] py3-canonicaljson
- [x] py3-deprecated
- [x] py3-openapi-codec
- [x] py3-pkgconfig
- [x] py3-pytools
- [x] py3-pastel
- [x] py3-pyaes
- [x] py3-shellingham
- [x] py3-pysimplesoap
- [x] py3-pyrsistent
- [x] spirv-headers
- [x] telegram-desktop
- [x] py3-soupsieve
- [x] py3-mimeparse
- [x] py3-path.py
- [x] py3-pem
- [x] shaderc
- [x] qimgv
- [x] ranger
- [x] py3-twine
- [x] py3-txsni
- [x] py3-signedjson
- [x] zola
- [x] py3-smmap2
- [ ] mingw-w64-binutils
- [x] py3-readme_renderer
- [ ] libdbusmenu-glib
- [x] vkd3d
- [x] quaternion
- [x] py3-tomlkit
- [x] libcorkipset
- [ ] libappindicator
- [x] poetry
- [x] py3-visitor
- [x] py3-cachecontrol
- [x] py3-pylev
- [x] totem-pl-parser
- [x] spirv-tools
- [x] woff2
- [x] adapta-gtk-theme
- [x] py3-unpaddedbase64
- [x] spdlog
- [x] wifish
- [x] snooze
- [x] py3-txacme
- [x] py3-libevdev
- [x] wmutils
- [x] py3-treq
- [x] starship
- [x] xidle
- [x] synapse
- [x] ttf-roboto
- [x] low-memory-monitor
- [x] range-v3
- [x] zchunk
- [x] yaru-themes
- [x] py3-typing-extensions
- [x] translate-shell

**Comment by maxice8** [comment]
First stage done by searching github urls on url= field of the APKBUILD.

done on f17dfdb

**Comment by maxice8** [comment]
- gyp
- exa
- cbindgen
- dxvk
- cmark
- buku
- fd
- elogind
- lab
- fish
- adapta-kde
- glslang
- gopass
- gotop
- grilo
- font-hermit-nerd
- imgbrd-grabber
- maim
- editline
- font-material-design-icons
- i3lock-color
- hyperfine
- libcotp
- libb2
- libbaseencode
- libbloom
- libcork
- light-locker
- lxqt-build-tools
- libquotient
- libsigc++3
- libplacebo
- slop
- kvantum
- materia-theme
- otpclient
- libxmlb
- py3-boltons
- libluv
- xdo
- py3-coreapi
- py3-django-rest-swagger
- py3-hypothesis
- py3-dominate
- py3-bleach
- powertop
- py3-pbkdf2
- py3-gitdb2
- py3-gitpython
- py3-eliot
- py3-deprecated
- py3-openapi-codec
- py3-pytools
- py3-shellingham
- py3-pyrsistent
- spirv-headers
- telegram-desktop
- py3-soupsieve
- py3-mimeparse
- py3-path.py
- py3-pem
- shaderc
- qimgv
- ranger
- py3-signedjson
- zola
- py3-smmap2
- quaternion
- libcorkipset
- poetry
- py3-visitor
- spirv-tools
- woff2
- adapta-gtk-theme
- py3-unpaddedbase64
- spdlog
- wifish
- snooze
- wmutils
- py3-treq
- starship
- range-v3
- yaru-themes
- translate-shell

**Comment by maxice8** [comment]
Done manually

- appstream
- dav1d
- libxkbcommon
- pulseaudio
- paprefs
- py3-invoke
- py3-twine
- vkd3d
- py3-libevdev
- totem-pl-parser
- low-memory-monitor
